//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TSTModel", "FK_TSTEmployees_TSTDepartments", "TSTDepartments", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TSTModel.TSTDepartment), "TSTEmployees", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TSTModel.TSTEmployee), true)]
[assembly: EdmRelationshipAttribute("TSTModel", "FK_TSTRequests_TSTEmployees", "TSTEmployees", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TSTModel.TSTEmployee), "TSTRequests", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TSTModel.TSTRequest), true)]
[assembly: EdmRelationshipAttribute("TSTModel", "FK_TSTRequests_TSTEmployees1", "TSTEmployees", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TSTModel.TSTEmployee), "TSTRequests", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TSTModel.TSTRequest), true)]
[assembly: EdmRelationshipAttribute("TSTModel", "FK_TSTRequests_TSTRequestStatuses", "TSTRequestStatuses", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TSTModel.TSTRequestStatus), "TSTRequests", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TSTModel.TSTRequest), true)]

#endregion

namespace TSTModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TSTEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TSTEntities object using the connection string found in the 'TSTEntities' section of the application configuration file.
        /// </summary>
        public TSTEntities() : base("name=TSTEntities", "TSTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TSTEntities object.
        /// </summary>
        public TSTEntities(string connectionString) : base(connectionString, "TSTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TSTEntities object.
        /// </summary>
        public TSTEntities(EntityConnection connection) : base(connection, "TSTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TSTDepartment> TSTDepartments
        {
            get
            {
                if ((_TSTDepartments == null))
                {
                    _TSTDepartments = base.CreateObjectSet<TSTDepartment>("TSTDepartments");
                }
                return _TSTDepartments;
            }
        }
        private ObjectSet<TSTDepartment> _TSTDepartments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TSTEmployee> TSTEmployees
        {
            get
            {
                if ((_TSTEmployees == null))
                {
                    _TSTEmployees = base.CreateObjectSet<TSTEmployee>("TSTEmployees");
                }
                return _TSTEmployees;
            }
        }
        private ObjectSet<TSTEmployee> _TSTEmployees;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TSTRequest> TSTRequests
        {
            get
            {
                if ((_TSTRequests == null))
                {
                    _TSTRequests = base.CreateObjectSet<TSTRequest>("TSTRequests");
                }
                return _TSTRequests;
            }
        }
        private ObjectSet<TSTRequest> _TSTRequests;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TSTRequestStatus> TSTRequestStatuses
        {
            get
            {
                if ((_TSTRequestStatuses == null))
                {
                    _TSTRequestStatuses = base.CreateObjectSet<TSTRequestStatus>("TSTRequestStatuses");
                }
                return _TSTRequestStatuses;
            }
        }
        private ObjectSet<TSTRequestStatus> _TSTRequestStatuses;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TSTDepartments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTSTDepartments(TSTDepartment tSTDepartment)
        {
            base.AddObject("TSTDepartments", tSTDepartment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TSTEmployees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTSTEmployees(TSTEmployee tSTEmployee)
        {
            base.AddObject("TSTEmployees", tSTEmployee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TSTRequests EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTSTRequests(TSTRequest tSTRequest)
        {
            base.AddObject("TSTRequests", tSTRequest);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TSTRequestStatuses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTSTRequestStatuses(TSTRequestStatus tSTRequestStatus)
        {
            base.AddObject("TSTRequestStatuses", tSTRequestStatus);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TSTModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value, "principal_id");
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value, "diagram_id");
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value, "version");
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true, "definition");
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TSTModel", Name="TSTDepartment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TSTDepartment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TSTDepartment object.
        /// </summary>
        /// <param name="departmentID">Initial value of the DepartmentID property.</param>
        /// <param name="departmentName">Initial value of the DepartmentName property.</param>
        public static TSTDepartment CreateTSTDepartment(global::System.Int32 departmentID, global::System.String departmentName)
        {
            TSTDepartment tSTDepartment = new TSTDepartment();
            tSTDepartment.DepartmentID = departmentID;
            tSTDepartment.DepartmentName = departmentName;
            return tSTDepartment;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DepartmentID
        {
            get
            {
                return _DepartmentID;
            }
            set
            {
                if (_DepartmentID != value)
                {
                    OnDepartmentIDChanging(value);
                    ReportPropertyChanging("DepartmentID");
                    _DepartmentID = StructuralObject.SetValidValue(value, "DepartmentID");
                    ReportPropertyChanged("DepartmentID");
                    OnDepartmentIDChanged();
                }
            }
        }
        private global::System.Int32 _DepartmentID;
        partial void OnDepartmentIDChanging(global::System.Int32 value);
        partial void OnDepartmentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DepartmentName
        {
            get
            {
                return _DepartmentName;
            }
            set
            {
                OnDepartmentNameChanging(value);
                ReportPropertyChanging("DepartmentName");
                _DepartmentName = StructuralObject.SetValidValue(value, false, "DepartmentName");
                ReportPropertyChanged("DepartmentName");
                OnDepartmentNameChanged();
            }
        }
        private global::System.String _DepartmentName;
        partial void OnDepartmentNameChanging(global::System.String value);
        partial void OnDepartmentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DepartmentDescription
        {
            get
            {
                return _DepartmentDescription;
            }
            set
            {
                OnDepartmentDescriptionChanging(value);
                ReportPropertyChanging("DepartmentDescription");
                _DepartmentDescription = StructuralObject.SetValidValue(value, true, "DepartmentDescription");
                ReportPropertyChanged("DepartmentDescription");
                OnDepartmentDescriptionChanged();
            }
        }
        private global::System.String _DepartmentDescription;
        partial void OnDepartmentDescriptionChanging(global::System.String value);
        partial void OnDepartmentDescriptionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TSTModel", "FK_TSTEmployees_TSTDepartments", "TSTEmployees")]
        public EntityCollection<TSTEmployee> TSTEmployees
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TSTEmployee>("TSTModel.FK_TSTEmployees_TSTDepartments", "TSTEmployees");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TSTEmployee>("TSTModel.FK_TSTEmployees_TSTDepartments", "TSTEmployees", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TSTModel", Name="TSTEmployee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TSTEmployee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TSTEmployee object.
        /// </summary>
        /// <param name="employeeID">Initial value of the EmployeeID property.</param>
        /// <param name="fName">Initial value of the FName property.</param>
        /// <param name="lName">Initial value of the LName property.</param>
        /// <param name="empDepartmentID">Initial value of the EmpDepartmentID property.</param>
        public static TSTEmployee CreateTSTEmployee(global::System.Int32 employeeID, global::System.String fName, global::System.String lName, global::System.Int32 empDepartmentID)
        {
            TSTEmployee tSTEmployee = new TSTEmployee();
            tSTEmployee.EmployeeID = employeeID;
            tSTEmployee.FName = fName;
            tSTEmployee.LName = lName;
            tSTEmployee.EmpDepartmentID = empDepartmentID;
            return tSTEmployee;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmployeeID
        {
            get
            {
                return _EmployeeID;
            }
            set
            {
                if (_EmployeeID != value)
                {
                    OnEmployeeIDChanging(value);
                    ReportPropertyChanging("EmployeeID");
                    _EmployeeID = StructuralObject.SetValidValue(value, "EmployeeID");
                    ReportPropertyChanged("EmployeeID");
                    OnEmployeeIDChanged();
                }
            }
        }
        private global::System.Int32 _EmployeeID;
        partial void OnEmployeeIDChanging(global::System.Int32 value);
        partial void OnEmployeeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true, "Title");
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FName
        {
            get
            {
                return _FName;
            }
            set
            {
                OnFNameChanging(value);
                ReportPropertyChanging("FName");
                _FName = StructuralObject.SetValidValue(value, false, "FName");
                ReportPropertyChanged("FName");
                OnFNameChanged();
            }
        }
        private global::System.String _FName;
        partial void OnFNameChanging(global::System.String value);
        partial void OnFNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LName
        {
            get
            {
                return _LName;
            }
            set
            {
                OnLNameChanging(value);
                ReportPropertyChanging("LName");
                _LName = StructuralObject.SetValidValue(value, false, "LName");
                ReportPropertyChanged("LName");
                OnLNameChanged();
            }
        }
        private global::System.String _LName;
        partial void OnLNameChanging(global::System.String value);
        partial void OnLNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true, "Phone");
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> HireDate
        {
            get
            {
                return _HireDate;
            }
            set
            {
                OnHireDateChanging(value);
                ReportPropertyChanging("HireDate");
                _HireDate = StructuralObject.SetValidValue(value, "HireDate");
                ReportPropertyChanged("HireDate");
                OnHireDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _HireDate;
        partial void OnHireDateChanging(Nullable<global::System.DateTime> value);
        partial void OnHireDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true, "Notes");
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes;
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value, "IsActive");
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmpDepartmentID
        {
            get
            {
                return _EmpDepartmentID;
            }
            set
            {
                OnEmpDepartmentIDChanging(value);
                ReportPropertyChanging("EmpDepartmentID");
                _EmpDepartmentID = StructuralObject.SetValidValue(value, "EmpDepartmentID");
                ReportPropertyChanged("EmpDepartmentID");
                OnEmpDepartmentIDChanged();
            }
        }
        private global::System.Int32 _EmpDepartmentID;
        partial void OnEmpDepartmentIDChanging(global::System.Int32 value);
        partial void OnEmpDepartmentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true, "Location");
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmployeeImage
        {
            get
            {
                return _EmployeeImage;
            }
            set
            {
                OnEmployeeImageChanging(value);
                ReportPropertyChanging("EmployeeImage");
                _EmployeeImage = StructuralObject.SetValidValue(value, true, "EmployeeImage");
                ReportPropertyChanged("EmployeeImage");
                OnEmployeeImageChanged();
            }
        }
        private global::System.String _EmployeeImage;
        partial void OnEmployeeImageChanging(global::System.String value);
        partial void OnEmployeeImageChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TSTModel", "FK_TSTEmployees_TSTDepartments", "TSTDepartments")]
        public TSTDepartment TSTDepartment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TSTDepartment>("TSTModel.FK_TSTEmployees_TSTDepartments", "TSTDepartments").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TSTDepartment>("TSTModel.FK_TSTEmployees_TSTDepartments", "TSTDepartments").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TSTDepartment> TSTDepartmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TSTDepartment>("TSTModel.FK_TSTEmployees_TSTDepartments", "TSTDepartments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TSTDepartment>("TSTModel.FK_TSTEmployees_TSTDepartments", "TSTDepartments", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TSTModel", "FK_TSTRequests_TSTEmployees", "TSTRequests")]
        public EntityCollection<TSTRequest> TSTRequests
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TSTRequest>("TSTModel.FK_TSTRequests_TSTEmployees", "TSTRequests");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TSTRequest>("TSTModel.FK_TSTRequests_TSTEmployees", "TSTRequests", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TSTModel", "FK_TSTRequests_TSTEmployees1", "TSTRequests")]
        public EntityCollection<TSTRequest> TSTRequests1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TSTRequest>("TSTModel.FK_TSTRequests_TSTEmployees1", "TSTRequests");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TSTRequest>("TSTModel.FK_TSTRequests_TSTEmployees1", "TSTRequests", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TSTModel", Name="TSTRequest")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TSTRequest : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TSTRequest object.
        /// </summary>
        /// <param name="requestID">Initial value of the RequestID property.</param>
        /// <param name="requestDate">Initial value of the RequestDate property.</param>
        /// <param name="requesterNotes">Initial value of the RequesterNotes property.</param>
        /// <param name="requestStatusID">Initial value of the RequestStatusID property.</param>
        /// <param name="requesterID">Initial value of the RequesterID property.</param>
        public static TSTRequest CreateTSTRequest(global::System.Int32 requestID, global::System.DateTime requestDate, global::System.String requesterNotes, global::System.Int32 requestStatusID, global::System.Int32 requesterID)
        {
            TSTRequest tSTRequest = new TSTRequest();
            tSTRequest.RequestID = requestID;
            tSTRequest.RequestDate = requestDate;
            tSTRequest.RequesterNotes = requesterNotes;
            tSTRequest.RequestStatusID = requestStatusID;
            tSTRequest.RequesterID = requesterID;
            return tSTRequest;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RequestID
        {
            get
            {
                return _RequestID;
            }
            set
            {
                if (_RequestID != value)
                {
                    OnRequestIDChanging(value);
                    ReportPropertyChanging("RequestID");
                    _RequestID = StructuralObject.SetValidValue(value, "RequestID");
                    ReportPropertyChanged("RequestID");
                    OnRequestIDChanged();
                }
            }
        }
        private global::System.Int32 _RequestID;
        partial void OnRequestIDChanging(global::System.Int32 value);
        partial void OnRequestIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime RequestDate
        {
            get
            {
                return _RequestDate;
            }
            set
            {
                OnRequestDateChanging(value);
                ReportPropertyChanging("RequestDate");
                _RequestDate = StructuralObject.SetValidValue(value, "RequestDate");
                ReportPropertyChanged("RequestDate");
                OnRequestDateChanged();
            }
        }
        private global::System.DateTime _RequestDate;
        partial void OnRequestDateChanging(global::System.DateTime value);
        partial void OnRequestDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ClosedDate
        {
            get
            {
                return _ClosedDate;
            }
            set
            {
                OnClosedDateChanging(value);
                ReportPropertyChanging("ClosedDate");
                _ClosedDate = StructuralObject.SetValidValue(value, "ClosedDate");
                ReportPropertyChanged("ClosedDate");
                OnClosedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ClosedDate;
        partial void OnClosedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnClosedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RequesterNotes
        {
            get
            {
                return _RequesterNotes;
            }
            set
            {
                OnRequesterNotesChanging(value);
                ReportPropertyChanging("RequesterNotes");
                _RequesterNotes = StructuralObject.SetValidValue(value, false, "RequesterNotes");
                ReportPropertyChanged("RequesterNotes");
                OnRequesterNotesChanged();
            }
        }
        private global::System.String _RequesterNotes;
        partial void OnRequesterNotesChanging(global::System.String value);
        partial void OnRequesterNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TechNotes
        {
            get
            {
                return _TechNotes;
            }
            set
            {
                OnTechNotesChanging(value);
                ReportPropertyChanging("TechNotes");
                _TechNotes = StructuralObject.SetValidValue(value, true, "TechNotes");
                ReportPropertyChanged("TechNotes");
                OnTechNotesChanged();
            }
        }
        private global::System.String _TechNotes;
        partial void OnTechNotesChanging(global::System.String value);
        partial void OnTechNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RequestStatusID
        {
            get
            {
                return _RequestStatusID;
            }
            set
            {
                OnRequestStatusIDChanging(value);
                ReportPropertyChanging("RequestStatusID");
                _RequestStatusID = StructuralObject.SetValidValue(value, "RequestStatusID");
                ReportPropertyChanged("RequestStatusID");
                OnRequestStatusIDChanged();
            }
        }
        private global::System.Int32 _RequestStatusID;
        partial void OnRequestStatusIDChanging(global::System.Int32 value);
        partial void OnRequestStatusIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RequesterID
        {
            get
            {
                return _RequesterID;
            }
            set
            {
                OnRequesterIDChanging(value);
                ReportPropertyChanging("RequesterID");
                _RequesterID = StructuralObject.SetValidValue(value, "RequesterID");
                ReportPropertyChanged("RequesterID");
                OnRequesterIDChanged();
            }
        }
        private global::System.Int32 _RequesterID;
        partial void OnRequesterIDChanging(global::System.Int32 value);
        partial void OnRequesterIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TechID
        {
            get
            {
                return _TechID;
            }
            set
            {
                OnTechIDChanging(value);
                ReportPropertyChanging("TechID");
                _TechID = StructuralObject.SetValidValue(value, "TechID");
                ReportPropertyChanged("TechID");
                OnTechIDChanged();
            }
        }
        private Nullable<global::System.Int32> _TechID;
        partial void OnTechIDChanging(Nullable<global::System.Int32> value);
        partial void OnTechIDChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TSTModel", "FK_TSTRequests_TSTEmployees", "TSTEmployees")]
        public TSTEmployee TSTEmployee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TSTEmployee>("TSTModel.FK_TSTRequests_TSTEmployees", "TSTEmployees").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TSTEmployee>("TSTModel.FK_TSTRequests_TSTEmployees", "TSTEmployees").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TSTEmployee> TSTEmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TSTEmployee>("TSTModel.FK_TSTRequests_TSTEmployees", "TSTEmployees");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TSTEmployee>("TSTModel.FK_TSTRequests_TSTEmployees", "TSTEmployees", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TSTModel", "FK_TSTRequests_TSTEmployees1", "TSTEmployees")]
        public TSTEmployee TSTEmployee1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TSTEmployee>("TSTModel.FK_TSTRequests_TSTEmployees1", "TSTEmployees").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TSTEmployee>("TSTModel.FK_TSTRequests_TSTEmployees1", "TSTEmployees").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TSTEmployee> TSTEmployee1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TSTEmployee>("TSTModel.FK_TSTRequests_TSTEmployees1", "TSTEmployees");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TSTEmployee>("TSTModel.FK_TSTRequests_TSTEmployees1", "TSTEmployees", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TSTModel", "FK_TSTRequests_TSTRequestStatuses", "TSTRequestStatuses")]
        public TSTRequestStatus TSTRequestStatus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TSTRequestStatus>("TSTModel.FK_TSTRequests_TSTRequestStatuses", "TSTRequestStatuses").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TSTRequestStatus>("TSTModel.FK_TSTRequests_TSTRequestStatuses", "TSTRequestStatuses").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TSTRequestStatus> TSTRequestStatusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TSTRequestStatus>("TSTModel.FK_TSTRequests_TSTRequestStatuses", "TSTRequestStatuses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TSTRequestStatus>("TSTModel.FK_TSTRequests_TSTRequestStatuses", "TSTRequestStatuses", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TSTModel", Name="TSTRequestStatus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TSTRequestStatus : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TSTRequestStatus object.
        /// </summary>
        /// <param name="requestStatusID">Initial value of the RequestStatusID property.</param>
        /// <param name="requestStatusDescription">Initial value of the RequestStatusDescription property.</param>
        public static TSTRequestStatus CreateTSTRequestStatus(global::System.Int32 requestStatusID, global::System.String requestStatusDescription)
        {
            TSTRequestStatus tSTRequestStatus = new TSTRequestStatus();
            tSTRequestStatus.RequestStatusID = requestStatusID;
            tSTRequestStatus.RequestStatusDescription = requestStatusDescription;
            return tSTRequestStatus;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RequestStatusID
        {
            get
            {
                return _RequestStatusID;
            }
            set
            {
                if (_RequestStatusID != value)
                {
                    OnRequestStatusIDChanging(value);
                    ReportPropertyChanging("RequestStatusID");
                    _RequestStatusID = StructuralObject.SetValidValue(value, "RequestStatusID");
                    ReportPropertyChanged("RequestStatusID");
                    OnRequestStatusIDChanged();
                }
            }
        }
        private global::System.Int32 _RequestStatusID;
        partial void OnRequestStatusIDChanging(global::System.Int32 value);
        partial void OnRequestStatusIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RequestStatusDescription
        {
            get
            {
                return _RequestStatusDescription;
            }
            set
            {
                OnRequestStatusDescriptionChanging(value);
                ReportPropertyChanging("RequestStatusDescription");
                _RequestStatusDescription = StructuralObject.SetValidValue(value, false, "RequestStatusDescription");
                ReportPropertyChanged("RequestStatusDescription");
                OnRequestStatusDescriptionChanged();
            }
        }
        private global::System.String _RequestStatusDescription;
        partial void OnRequestStatusDescriptionChanging(global::System.String value);
        partial void OnRequestStatusDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RequestStatusNotes
        {
            get
            {
                return _RequestStatusNotes;
            }
            set
            {
                OnRequestStatusNotesChanging(value);
                ReportPropertyChanging("RequestStatusNotes");
                _RequestStatusNotes = StructuralObject.SetValidValue(value, true, "RequestStatusNotes");
                ReportPropertyChanged("RequestStatusNotes");
                OnRequestStatusNotesChanged();
            }
        }
        private global::System.String _RequestStatusNotes;
        partial void OnRequestStatusNotesChanging(global::System.String value);
        partial void OnRequestStatusNotesChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TSTModel", "FK_TSTRequests_TSTRequestStatuses", "TSTRequests")]
        public EntityCollection<TSTRequest> TSTRequests
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TSTRequest>("TSTModel.FK_TSTRequests_TSTRequestStatuses", "TSTRequests");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TSTRequest>("TSTModel.FK_TSTRequests_TSTRequestStatuses", "TSTRequests", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
